export const subjectsData = [
    {
        id: 'mathematics',
        name: 'Mathematics',
        code: 'MAT',
        description: 'Algebra, Calculus, Geometry and Mathematical Literacy',
        progress: 75,
        target: 80,
        averageScore: 72,
        studyHours: 18,
        assignmentsCompleted: 12,
        upcomingDeadlines: 2,
        strength: 'Algebra',
        weakness: 'Calculus',
        lastActivity: '2 days ago',
        color: 'bg-blue-500',
        textColor: 'text-blue-600',
        borderColor: 'border-blue-200'
    },
    {
        id: 'physical-sciences',
        name: 'Physical Sciences',
        code: 'PSC',
        description: 'Physics and Chemistry fundamentals',
        progress: 68,
        target: 75,
        averageScore: 65,
        studyHours: 15,
        assignmentsCompleted: 8,
        upcomingDeadlines: 3,
        strength: 'Chemistry',
        weakness: 'Physics',
        lastActivity: '1 day ago',
        color: 'bg-purple-500',
        textColor: 'text-purple-600',
        borderColor: 'border-purple-200'
    },
    {
        id: 'life-sciences',
        name: 'Life Sciences',
        code: 'LSC',
        description: 'Biology, Ecology and Human Anatomy',
        progress: 82,
        target: 78,
        averageScore: 79,
        studyHours: 12,
        assignmentsCompleted: 10,
        upcomingDeadlines: 1,
        strength: 'Human Biology',
        weakness: 'Ecology',
        lastActivity: '3 days ago',
        color: 'bg-green-500',
        textColor: 'text-green-600',
        borderColor: 'border-green-200'
    },
    {
        id: 'english',
        name: 'English Home Language',
        code: 'ENG',
        description: 'Language, Literature and Communication',
        progress: 88,
        target: 85,
        averageScore: 84,
        studyHours: 10,
        assignmentsCompleted: 15,
        upcomingDeadlines: 0,
        strength: 'Literature',
        weakness: 'Creative Writing',
        lastActivity: 'Today',
        color: 'bg-red-500',
        textColor: 'text-red-600',
        borderColor: 'border-red-200'
    },
    {
        id: 'afrikaans',
        name: 'Afrikaans FAL',
        code: 'AFR',
        description: 'First Additional Language - Reading and Writing',
        progress: 65,
        target: 70,
        averageScore: 62,
        studyHours: 8,
        assignmentsCompleted: 6,
        upcomingDeadlines: 2,
        strength: 'Reading',
        weakness: 'Writing',
        lastActivity: '4 days ago',
        color: 'bg-orange-500',
        textColor: 'text-orange-600',
        borderColor: 'border-orange-200'
    },
    {
        id: 'geography',
        name: 'Geography',
        code: 'GEO',
        description: 'Physical and Human Geography',
        progress: 72,
        target: 75,
        averageScore: 70,
        studyHours: 9,
        assignmentsCompleted: 7,
        upcomingDeadlines: 1,
        strength: 'Map Work',
        weakness: 'Climate Studies',
        lastActivity: '2 days ago',
        color: 'bg-cyan-500',
        textColor: 'text-cyan-600',
        borderColor: 'border-cyan-200'
    },
    {
        id: 'accounting',
        name: 'Accounting',
        code: 'ACC',
        description: 'Financial Accounting and Business Principles',
        progress: 79,
        target: 82,
        averageScore: 76,
        studyHours: 14,
        assignmentsCompleted: 9,
        upcomingDeadlines: 2,
        strength: 'Financial Statements',
        weakness: 'Cost Accounting',
        lastActivity: 'Yesterday',
        color: 'bg-indigo-500',
        textColor: 'text-indigo-600',
        borderColor: 'border-indigo-200'
    },
    {
        id: 'business-studies',
        name: 'Business Studies',
        code: 'BUS',
        description: 'Business Management and Entrepreneurship',
        progress: 85,
        target: 80,
        averageScore: 82,
        studyHours: 11,
        assignmentsCompleted: 11,
        upcomingDeadlines: 1,
        strength: 'Business Management',
        weakness: 'Entrepreneurship',
        lastActivity: 'Today',
        color: 'bg-emerald-500',
        textColor: 'text-emerald-600',
        borderColor: 'border-emerald-200'
    }
]